"use client";

import { useEffect, useState, useCallback } from "react";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Mail,
  Search,
  Pencil,
  Trash2,
  Copy,
  Download,
  Plus,
  Send,
  ChevronLeft,
  ChevronRight,
  FileText,
  Users,
  LayoutTemplate,
  Sparkles,
  Loader2,
  RefreshCw,
  Check,
  SkipForward,
  ClipboardCopy,
  ListChecks,
} from "lucide-react";
import { toast } from "sonner";
import { mergeTemplate, generateEml, type MergeContext } from "@/lib/merge-fields";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface Chef {
  id: string;
  name: string;
  slug: string;
  city: string | null;
  country: string | null;
  currentRestaurant: string | null;
  totalScore: number;
  contact?: ContactInfo | null;
  accolades?: { type: string; detail: string | null }[];
}

interface ContactInfo {
  id?: string;
  email: string | null;
  agentName: string | null;
  agentEmail: string | null;
  restaurantEmail: string | null;
  phone: string | null;
  preferredContactMethod: string | null;
  linkedinUrl: string | null;
  notes: string | null;
}

interface Draft {
  id: string;
  chefId: string;
  templateId: string | null;
  toEmail: string | null;
  subject: string;
  body: string;
  status: string;
  isAutoGenerated: boolean;
  dataPointsUsed: string | null;
  confidence: string | null;
  previousDraftId: string | null;
  createdAt: string;
  chef: { name: string; slug: string; currentRestaurant: string | null };
}

interface Template {
  id: string;
  name: string;
  category: string | null;
  subject: string;
  body: string;
  isDefault: boolean;
  createdAt: string;
}

interface SenderSettings {
  name: string;
  title: string;
  company: string;
  email: string;
}

const EMPTY_CONTACT: ContactInfo = {
  email: null,
  agentName: null,
  agentEmail: null,
  restaurantEmail: null,
  phone: null,
  preferredContactMethod: null,
  linkedinUrl: null,
  notes: null,
};

const STATUS_COLORS: Record<string, string> = {
  drafted: "bg-gray-100 text-gray-700",
  reviewed: "bg-yellow-100 text-yellow-700",
  ready_to_send: "bg-indigo-100 text-indigo-700",
  sent: "bg-blue-100 text-blue-700",
  replied: "bg-green-100 text-green-700",
  declined: "bg-red-100 text-red-700",
  confirmed: "bg-emerald-100 text-emerald-700",
  archived: "bg-muted text-muted-foreground",
};

function hasContact(chef: Chef): boolean {
  const c = chef.contact;
  if (!c) return false;
  return !!(c.email || c.agentEmail || c.restaurantEmail);
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default function OutreachPage() {
  const [activeTab, setActiveTab] = useState("directory");

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold flex items-center gap-2">
        <Mail className="h-6 w-6" /> Outreach
      </h1>

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="directory" className="gap-1">
            <Users className="h-4 w-4" /> Directory
          </TabsTrigger>
          <TabsTrigger value="drafts" className="gap-1">
            <FileText className="h-4 w-4" /> Drafts
          </TabsTrigger>
        </TabsList>

        <TabsContent value="directory">
          <DirectoryTab />
        </TabsContent>
        <TabsContent value="drafts">
          <DraftsTab />
        </TabsContent>
      </Tabs>
    </div>
  );
}

// ===========================================================================
// Tab 1: Contact Directory
// ===========================================================================

function DirectoryTab() {
  const [chefs, setChefs] = useState<Chef[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<"all" | "has" | "missing">("all");

  const [generatingId, setGeneratingId] = useState<string | null>(null);

  // Edit dialog
  const [editSlug, setEditSlug] = useState<string | null>(null);
  const [editContact, setEditContact] = useState<ContactInfo>(EMPTY_CONTACT);
  const [editLoading, setEditLoading] = useState(false);
  const [editSaving, setEditSaving] = useState(false);

  const fetchChefs = useCallback(() => {
    setLoading(true);
    fetch("/api/chefs?limit=200")
      .then((r) => r.json())
      .then((data) => setChefs(data.chefs ?? []))
      .catch(() => toast.error("Failed to load chefs"))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => { fetchChefs(); }, [fetchChefs]);

  const filtered = chefs.filter((c) => {
    if (search && !c.name.toLowerCase().includes(search.toLowerCase())) return false;
    if (filter === "has" && !hasContact(c)) return false;
    if (filter === "missing" && hasContact(c)) return false;
    return true;
  });

  const missingCount = chefs.filter((c) => !hasContact(c)).length;

  function openEdit(slug: string) {
    setEditSlug(slug);
    setEditLoading(true);
    fetch(`/api/chefs/${slug}/contact`)
      .then((r) => r.json())
      .then((data) => {
        setEditContact({
          email: data.email ?? null,
          agentName: data.agentName ?? null,
          agentEmail: data.agentEmail ?? null,
          restaurantEmail: data.restaurantEmail ?? null,
          phone: data.phone ?? null,
          preferredContactMethod: data.preferredContactMethod ?? null,
          linkedinUrl: data.linkedinUrl ?? null,
          notes: data.notes ?? null,
        });
      })
      .catch(() => setEditContact(EMPTY_CONTACT))
      .finally(() => setEditLoading(false));
  }

  function saveContact() {
    if (!editSlug) return;
    setEditSaving(true);
    fetch(`/api/chefs/${editSlug}/contact`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(editContact),
    })
      .then((r) => {
        if (!r.ok) throw new Error();
        toast.success("Contact updated");
        setEditSlug(null);
        fetchChefs();
      })
      .catch(() => toast.error("Failed to save contact"))
      .finally(() => setEditSaving(false));
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-3">
        <div className="relative flex-1 min-w-[200px] max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search chefs..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9"
          />
        </div>
        <div className="flex gap-1">
          {(["all", "has", "missing"] as const).map((v) => (
            <Button
              key={v}
              variant={filter === v ? "default" : "outline"}
              size="sm"
              onClick={() => setFilter(v)}
            >
              {v === "all" ? "All" : v === "has" ? "Has Contact" : "Missing Contact"}
            </Button>
          ))}
        </div>
        {missingCount > 0 && (
          <Badge variant="destructive">{missingCount} missing contact</Badge>
        )}
      </div>

      {loading ? (
        <div className="space-y-2">
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className="h-12 w-full" />
          ))}
        </div>
      ) : filtered.length === 0 ? (
        <Card>
          <CardContent className="p-8 text-center text-muted-foreground">No chefs found.</CardContent>
        </Card>
      ) : (
        <div className="border rounded-md overflow-auto">
          <table className="w-full text-sm">
            <thead className="bg-muted/50">
              <tr>
                <th className="text-left p-3 font-medium">Chef</th>
                <th className="text-left p-3 font-medium">Email</th>
                <th className="text-left p-3 font-medium">Agent / Manager</th>
                <th className="text-left p-3 font-medium">Restaurant Email</th>
                <th className="text-left p-3 font-medium">Preferred</th>
                <th className="text-left p-3 font-medium">Notes</th>
                <th className="p-3" />
              </tr>
            </thead>
            <tbody>
              {filtered.map((chef) => {
                const c = chef.contact;
                return (
                  <tr key={chef.id} className="border-t hover:bg-muted/30">
                    <td className="p-3">
                      <Link href={`/chefs/${chef.slug}`} className="font-medium text-primary hover:underline">
                        {chef.name}
                      </Link>
                    </td>
                    <td className="p-3 text-muted-foreground">{c?.email || "-"}</td>
                    <td className="p-3 text-muted-foreground">
                      {c?.agentName || c?.agentEmail
                        ? `${c.agentName || ""}${c.agentName && c.agentEmail ? " / " : ""}${c.agentEmail || ""}`
                        : "-"}
                    </td>
                    <td className="p-3 text-muted-foreground">{c?.restaurantEmail || "-"}</td>
                    <td className="p-3 text-muted-foreground">{c?.preferredContactMethod || "-"}</td>
                    <td className="p-3 text-muted-foreground max-w-[200px] truncate">{c?.notes || "-"}</td>
                    <td className="p-3 text-right whitespace-nowrap space-x-1">
                      <Button size="sm" variant="ghost" onClick={() => openEdit(chef.slug)}>
                        <Pencil className="h-3.5 w-3.5" />
                      </Button>
                      <Button size="sm" variant="outline" disabled={generatingId === chef.id} onClick={async () => {
                        setGeneratingId(chef.id);
                        try {
                          const res = await fetch("/api/outreach/generate", {
                            method: "POST",
                            headers: { "Content-Type": "application/json" },
                            body: JSON.stringify({ chefId: chef.id }),
                          });
                          const data = await res.json();
                          if (!res.ok) throw new Error(data.error || "Failed");
                          toast.success(`Draft generated for ${chef.name}`);
                        } catch (err) {
                          toast.error((err as Error).message);
                        } finally {
                          setGeneratingId(null);
                        }
                      }}>
                        {generatingId === chef.id ? <Loader2 className="h-3.5 w-3.5 mr-1 animate-spin" /> : <Sparkles className="h-3.5 w-3.5 mr-1" />}
                        {generatingId === chef.id ? "..." : "Auto-Draft"}
                      </Button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Edit Contact Dialog */}
      <Dialog open={!!editSlug} onOpenChange={(open) => { if (!open) setEditSlug(null); }}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>Edit Contact</DialogTitle>
          </DialogHeader>
          {editLoading ? (
            <div className="space-y-3 py-4">
              {Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} className="h-10 w-full" />)}
            </div>
          ) : (
            <div className="space-y-3 py-2">
              {([
                ["email", "Email"],
                ["agentName", "Agent Name"],
                ["agentEmail", "Agent Email"],
                ["restaurantEmail", "Restaurant Email"],
                ["phone", "Phone"],
                ["preferredContactMethod", "Preferred Contact"],
                ["linkedinUrl", "LinkedIn URL"],
              ] as [keyof ContactInfo, string][]).map(([key, label]) => (
                <div key={key} className="grid grid-cols-3 gap-2 items-center">
                  <Label className="text-right">{label}</Label>
                  <Input
                    className="col-span-2"
                    value={(editContact[key] as string) || ""}
                    onChange={(e) => setEditContact((prev) => ({ ...prev, [key]: e.target.value || null }))}
                  />
                </div>
              ))}
              <div className="grid grid-cols-3 gap-2 items-start">
                <Label className="text-right pt-2">Notes</Label>
                <Textarea
                  className="col-span-2"
                  rows={3}
                  value={editContact.notes || ""}
                  onChange={(e) => setEditContact((prev) => ({ ...prev, notes: e.target.value || null }))}
                />
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setEditSlug(null)}>Cancel</Button>
            <Button onClick={saveContact} disabled={editSaving}>
              {editSaving ? "Saving..." : "Save"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// ===========================================================================
// Tab 2: Draft History
// ===========================================================================

function DraftsTab() {
  const [drafts, setDrafts] = useState<Draft[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(0);
  const limit = 20;

  // Detail dialog
  const [selected, setSelected] = useState<Draft | null>(null);
  const [detailStatus, setDetailStatus] = useState("");

  const fetchDrafts = useCallback(() => {
    setLoading(true);
    fetch(`/api/outreach/drafts?limit=${limit}&offset=${page * limit}`)
      .then((r) => r.json())
      .then((data) => { setDrafts(data.drafts ?? []); setTotal(data.total ?? 0); })
      .catch(() => toast.error("Failed to load drafts"))
      .finally(() => setLoading(false));
  }, [page]);

  useEffect(() => { fetchDrafts(); }, [fetchDrafts]);

  function openDetail(draft: Draft) {
    setSelected(draft);
    setDetailStatus(draft.status);
  }

  function updateStatus() {
    if (!selected) return;
    fetch(`/api/outreach/drafts/${selected.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status: detailStatus }),
    })
      .then((r) => {
        if (!r.ok) throw new Error();
        toast.success("Status updated");
        setSelected(null);
        fetchDrafts();
      })
      .catch(() => toast.error("Failed to update status"));
  }

  function deleteDraft() {
    if (!selected) return;
    fetch(`/api/outreach/drafts/${selected.id}`, { method: "DELETE" })
      .then((r) => {
        if (!r.ok) throw new Error();
        toast.success("Draft deleted");
        setSelected(null);
        fetchDrafts();
      })
      .catch(() => toast.error("Failed to delete draft"));
  }

  function copyDraft() {
    if (!selected) return;
    navigator.clipboard.writeText(`${selected.subject}\n${selected.body}`)
      .then(() => toast.success("Copied to clipboard"))
      .catch(() => toast.error("Copy failed"));
  }

  const totalPages = Math.ceil(total / limit);

  return (
    <div className="space-y-4">
      {loading ? (
        <div className="space-y-2">
          {Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-12 w-full" />)}
        </div>
      ) : drafts.length === 0 ? (
        <Card>
          <CardContent className="p-8 text-center text-muted-foreground">No drafts yet.</CardContent>
        </Card>
      ) : (
        <>
          <div className="border rounded-md overflow-auto">
            <table className="w-full text-sm">
              <thead className="bg-muted/50">
                <tr>
                  <th className="text-left p-3 font-medium">Chef</th>
                  <th className="text-left p-3 font-medium">Subject</th>
                  <th className="text-left p-3 font-medium">Template</th>
                  <th className="text-left p-3 font-medium">Created</th>
                  <th className="text-left p-3 font-medium">Status</th>
                </tr>
              </thead>
              <tbody>
                {drafts.map((d) => (
                  <tr
                    key={d.id}
                    className="border-t hover:bg-muted/30 cursor-pointer"
                    onClick={() => openDetail(d)}
                  >
                    <td className="p-3 font-medium">{d.chef.name}</td>
                    <td className="p-3 text-muted-foreground max-w-[300px] truncate">{d.subject}</td>
                    <td className="p-3 text-muted-foreground">{d.templateId || "-"}</td>
                    <td className="p-3 text-muted-foreground">{new Date(d.createdAt).toLocaleDateString()}</td>
                    <td className="p-3">
                      <span className={`inline-block px-2 py-0.5 rounded text-xs font-medium ${STATUS_COLORS[d.status] || ""}`}>
                        {d.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {totalPages > 1 && (
            <div className="flex items-center justify-center gap-2">
              <Button size="sm" variant="outline" disabled={page === 0} onClick={() => setPage((p) => p - 1)}>
                <ChevronLeft className="h-4 w-4" />
              </Button>
              <span className="text-sm text-muted-foreground">
                Page {page + 1} of {totalPages}
              </span>
              <Button size="sm" variant="outline" disabled={page >= totalPages - 1} onClick={() => setPage((p) => p + 1)}>
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
          )}
        </>
      )}

      {/* Draft Detail Dialog */}
      <Dialog open={!!selected} onOpenChange={(open) => { if (!open) setSelected(null); }}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{selected?.chef.name} - Draft</DialogTitle>
          </DialogHeader>
          {selected && (
            <div className="space-y-4">
              <div>
                <Label className="text-xs text-muted-foreground">Subject</Label>
                <p className="font-medium">{selected.subject}</p>
              </div>
              <Separator />
              <div>
                <Label className="text-xs text-muted-foreground">Body</Label>
                <pre className="mt-1 whitespace-pre-wrap text-sm bg-muted/30 rounded p-3">{selected.body}</pre>
              </div>
              <Separator />
              <div className="flex items-center gap-3">
                <Label>Status</Label>
                <Select value={detailStatus} onValueChange={setDetailStatus}>
                  <SelectTrigger className="w-40">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {["drafted", "sent", "replied", "declined", "confirmed", "archived"].map((s) => (
                      <SelectItem key={s} value={s}>{s}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {detailStatus !== selected.status && (
                  <Button size="sm" onClick={updateStatus}>Update</Button>
                )}
              </div>
            </div>
          )}
          <DialogFooter className="flex gap-2">
            <Button variant="outline" onClick={copyDraft}>
              <Copy className="h-4 w-4 mr-1" /> Copy
            </Button>
            <Button variant="destructive" onClick={deleteDraft}>
              <Trash2 className="h-4 w-4 mr-1" /> Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// ===========================================================================
// Tab 3: Compose
// ===========================================================================

function ComposeTab({
  preselectedSlug,
  clearPreselected,
}: {
  preselectedSlug: string | null;
  clearPreselected: () => void;
}) {
  const [chefs, setChefs] = useState<Chef[]>([]);
  const [templates, setTemplates] = useState<Template[]>([]);
  const [sender, setSender] = useState<SenderSettings>({ name: "", title: "", company: "", email: "" });

  const [selectedSlug, setSelectedSlug] = useState<string>("");
  const [selectedTemplateId, setSelectedTemplateId] = useState<string>("");
  const [customNote, setCustomNote] = useState("");
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [saving, setSaving] = useState(false);

  // Load chefs, templates, sender
  useEffect(() => {
    fetch("/api/chefs?limit=200").then((r) => r.json()).then((d) => setChefs(d.chefs ?? [])).catch(() => {});
    fetch("/api/templates").then((r) => r.json()).then((d) => setTemplates(d ?? [])).catch(() => {});
    fetch("/api/settings/sender").then((r) => r.json()).then(setSender).catch(() => {});
  }, []);

  // Handle preselected slug from directory
  useEffect(() => {
    if (preselectedSlug) {
      setSelectedSlug(preselectedSlug);
      clearPreselected();
    }
  }, [preselectedSlug, clearPreselected]);

  // Merge preview when chef + template selected
  useEffect(() => {
    if (!selectedSlug || !selectedTemplateId) return;

    const tpl = templates.find((t) => t.id === selectedTemplateId);
    if (!tpl) return;

    fetch(`/api/chefs/${selectedSlug}`)
      .then((r) => r.json())
      .then((chef) => {
        const topAccolade =
          chef.accolades?.[0]
            ? `${chef.accolades[0].type}${chef.accolades[0].detail ? ` (${chef.accolades[0].detail})` : ""}`
            : "";

        const ctx: MergeContext = {
          chefName: chef.name,
          restaurantName: chef.currentRestaurant || "",
          topAccolade,
          city: chef.city || "",
          senderName: sender.name,
          senderTitle: sender.title,
          senderCompany: sender.company,
          customNote,
        };

        setSubject(mergeTemplate(tpl.subject, ctx));
        setBody(mergeTemplate(tpl.body, ctx));
      })
      .catch(() => toast.error("Failed to load chef details"));
  }, [selectedSlug, selectedTemplateId, customNote, templates, sender]);

  function copyToClipboard() {
    if (!subject && !body) {
      toast.error("Nothing to copy");
      return;
    }
    navigator.clipboard.writeText(`${subject}\n${body}`)
      .then(() => toast.success("Copied to clipboard"))
      .catch(() => toast.error("Copy failed"));
  }

  function downloadEml() {
    const chef = chefs.find((c) => c.slug === selectedSlug);
    const toEmail = chef?.contact?.email || chef?.contact?.agentEmail || chef?.contact?.restaurantEmail || "";
    const fromEmail = sender.email || undefined;
    const eml = generateEml(toEmail, subject, body, fromEmail);
    const blob = new Blob([eml], { type: "message/rfc822" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `outreach-${selectedSlug || "draft"}.eml`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Downloaded .eml file");
  }

  function saveDraft() {
    const chef = chefs.find((c) => c.slug === selectedSlug);
    if (!chef) {
      toast.error("Select a chef first");
      return;
    }
    if (!subject.trim()) {
      toast.error("Subject is required");
      return;
    }
    setSaving(true);
    fetch("/api/outreach/drafts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chefId: chef.id,
        templateId: selectedTemplateId || null,
        toEmail: chef.contact?.email || chef.contact?.agentEmail || null,
        subject,
        body,
      }),
    })
      .then((r) => {
        if (!r.ok) throw new Error();
        toast.success("Draft saved");
        setSubject("");
        setBody("");
        setCustomNote("");
      })
      .catch(() => toast.error("Failed to save draft"))
      .finally(() => setSaving(false));
  }

  return (
    <div className="space-y-6 max-w-3xl">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="space-y-2">
          <Label>Chef</Label>
          <Select value={selectedSlug} onValueChange={setSelectedSlug}>
            <SelectTrigger>
              <SelectValue placeholder="Select chef..." />
            </SelectTrigger>
            <SelectContent>
              {chefs.map((c) => (
                <SelectItem key={c.slug} value={c.slug}>{c.name}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label>Template</Label>
          <Select value={selectedTemplateId} onValueChange={setSelectedTemplateId}>
            <SelectTrigger>
              <SelectValue placeholder="Select template..." />
            </SelectTrigger>
            <SelectContent>
              {templates.map((t) => (
                <SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      <div className="space-y-2">
        <Label>Custom Note (fills {"{{custom_note}}"})</Label>
        <Textarea
          rows={2}
          value={customNote}
          onChange={(e) => setCustomNote(e.target.value)}
          placeholder="Optional personal note..."
        />
      </div>

      <Separator />

      <div className="space-y-2">
        <Label>Subject</Label>
        <Input value={subject} onChange={(e) => setSubject(e.target.value)} />
      </div>

      <div className="space-y-2">
        <Label>Body</Label>
        <Textarea rows={14} value={body} onChange={(e) => setBody(e.target.value)} />
      </div>

      <div className="flex flex-wrap gap-3">
        <Button size="lg" onClick={copyToClipboard}>
          <Copy className="h-4 w-4 mr-2" /> Copy to Clipboard
        </Button>
        <Button variant="outline" onClick={downloadEml}>
          <Download className="h-4 w-4 mr-2" /> Download .eml
        </Button>
        <Button variant="secondary" onClick={saveDraft} disabled={saving}>
          <FileText className="h-4 w-4 mr-2" /> {saving ? "Saving..." : "Save Draft"}
        </Button>
      </div>
    </div>
  );
}

// ===========================================================================
// Tab 4: Templates
// ===========================================================================

function TemplatesTab() {
  const [templates, setTemplates] = useState<Template[]>([]);
  const [loading, setLoading] = useState(true);

  // Dialog state
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState({ name: "", category: "", subject: "", body: "" });
  const [formSaving, setFormSaving] = useState(false);

  // Delete confirmation
  const [deleteId, setDeleteId] = useState<string | null>(null);

  const fetchTemplates = useCallback(() => {
    setLoading(true);
    fetch("/api/templates")
      .then((r) => r.json())
      .then((d) => setTemplates(d ?? []))
      .catch(() => toast.error("Failed to load templates"))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => { fetchTemplates(); }, [fetchTemplates]);

  function openNew() {
    setEditingId(null);
    setForm({ name: "", category: "", subject: "", body: "" });
    setDialogOpen(true);
  }

  function openEdit(tpl: Template) {
    setEditingId(tpl.id);
    setForm({ name: tpl.name, category: tpl.category || "", subject: tpl.subject, body: tpl.body });
    setDialogOpen(true);
  }

  function duplicate(tpl: Template) {
    setEditingId(null);
    setForm({ name: `${tpl.name} (copy)`, category: tpl.category || "", subject: tpl.subject, body: tpl.body });
    setDialogOpen(true);
  }

  function saveTemplate() {
    if (!form.name.trim() || !form.subject.trim()) {
      toast.error("Name and subject are required");
      return;
    }
    setFormSaving(true);

    const url = editingId ? `/api/templates/${editingId}` : "/api/templates";
    const method = editingId ? "PUT" : "POST";

    fetch(url, {
      method,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(form),
    })
      .then((r) => {
        if (!r.ok) throw new Error();
        toast.success(editingId ? "Template updated" : "Template created");
        setDialogOpen(false);
        fetchTemplates();
      })
      .catch(() => toast.error("Failed to save template"))
      .finally(() => setFormSaving(false));
  }

  function confirmDelete() {
    if (!deleteId) return;
    fetch(`/api/templates/${deleteId}`, { method: "DELETE" })
      .then((r) => {
        if (!r.ok) throw new Error();
        toast.success("Template deleted");
        setDeleteId(null);
        fetchTemplates();
      })
      .catch(() => toast.error("Failed to delete template"));
  }

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center">
        <h2 className="text-lg font-semibold">Email Templates</h2>
        <Button onClick={openNew}>
          <Plus className="h-4 w-4 mr-1" /> New Template
        </Button>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {Array.from({ length: 4 }).map((_, i) => (
            <Card key={i}><CardContent className="p-4 space-y-2">
              <Skeleton className="h-5 w-3/4" />
              <Skeleton className="h-4 w-1/2" />
            </CardContent></Card>
          ))}
        </div>
      ) : templates.length === 0 ? (
        <Card>
          <CardContent className="p-8 text-center text-muted-foreground">No templates yet. Create one to get started.</CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {templates.map((tpl) => (
            <Card key={tpl.id} className="hover:shadow-md transition-shadow">
              <CardHeader className="pb-2">
                <div className="flex items-start justify-between">
                  <div>
                    <CardTitle className="text-base">{tpl.name}</CardTitle>
                    {tpl.category && (
                      <Badge variant="secondary" className="mt-1 text-xs">{tpl.category}</Badge>
                    )}
                  </div>
                  {tpl.isDefault && <Badge variant="outline">Default</Badge>}
                </div>
              </CardHeader>
              <CardContent className="space-y-2">
                <p className="text-sm text-muted-foreground truncate">
                  <span className="font-medium">Subject:</span> {tpl.subject}
                </p>
                <p className="text-sm text-muted-foreground line-clamp-2">{tpl.body}</p>
                <div className="flex gap-2 pt-2">
                  <Button size="sm" variant="outline" onClick={() => openEdit(tpl)}>
                    <Pencil className="h-3.5 w-3.5 mr-1" /> Edit
                  </Button>
                  <Button size="sm" variant="ghost" onClick={() => duplicate(tpl)}>
                    <Copy className="h-3.5 w-3.5 mr-1" /> Duplicate
                  </Button>
                  {!tpl.isDefault && (
                    <Button size="sm" variant="ghost" className="text-destructive" onClick={() => setDeleteId(tpl.id)}>
                      <Trash2 className="h-3.5 w-3.5" />
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Edit / Create Dialog */}
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>{editingId ? "Edit Template" : "New Template"}</DialogTitle>
          </DialogHeader>
          <div className="space-y-3 py-2">
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1">
                <Label>Name</Label>
                <Input value={form.name} onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))} />
              </div>
              <div className="space-y-1">
                <Label>Category</Label>
                <Input value={form.category} onChange={(e) => setForm((f) => ({ ...f, category: e.target.value }))} placeholder="e.g. initial, follow-up" />
              </div>
            </div>
            <div className="space-y-1">
              <Label>Subject</Label>
              <Input value={form.subject} onChange={(e) => setForm((f) => ({ ...f, subject: e.target.value }))} />
            </div>
            <div className="space-y-1">
              <Label>Body</Label>
              <Textarea rows={12} value={form.body} onChange={(e) => setForm((f) => ({ ...f, body: e.target.value }))} />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogOpen(false)}>Cancel</Button>
            <Button onClick={saveTemplate} disabled={formSaving}>
              {formSaving ? "Saving..." : editingId ? "Update" : "Create"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={!!deleteId} onOpenChange={(open) => { if (!open) setDeleteId(null); }}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Delete Template</DialogTitle>
          </DialogHeader>
          <p className="text-sm text-muted-foreground">
            Are you sure you want to delete this template? This action cannot be undone.
          </p>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteId(null)}>Cancel</Button>
            <Button variant="destructive" onClick={confirmDelete}>Delete</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Review Queue Tab
// ---------------------------------------------------------------------------

function ReviewQueueTab() {
  const [drafts, setDrafts] = useState<Draft[]>([]);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [loading, setLoading] = useState(true);
  const [editSubject, setEditSubject] = useState("");
  const [editBody, setEditBody] = useState("");
  const [regenerating, setRegenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [autoGenerating, setAutoGenerating] = useState(false);
  const [autoProgress, setAutoProgress] = useState("");

  const fetchDrafts = useCallback(async () => {
    setLoading(true);
    const res = await fetch("/api/outreach/drafts?status=drafted&limit=100");
    const data = await res.json();
    const autoOnly = (data.drafts || []).filter((d: Draft) => d.isAutoGenerated);
    setDrafts(autoOnly);
    setCurrentIdx(0);
    if (autoOnly.length > 0) {
      setEditSubject(autoOnly[0].subject);
      setEditBody(autoOnly[0].body);
    }
    setLoading(false);
  }, []);

  useEffect(() => { fetchDrafts(); }, [fetchDrafts]);

  const current = drafts[currentIdx] || null;

  function goTo(idx: number) {
    if (idx >= 0 && idx < drafts.length) {
      setCurrentIdx(idx);
      setEditSubject(drafts[idx].subject);
      setEditBody(drafts[idx].body);
      setCopied(false);
    }
  }

  async function approve() {
    if (!current) return;
    // Save any edits first
    await fetch(`/api/outreach/drafts/${current.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        subject: editSubject,
        body: editBody,
        status: "ready_to_send",
      }),
    });
    toast.success(`Approved draft for ${current.chef.name}`);
    const next = drafts.filter((_, i) => i !== currentIdx);
    setDrafts(next);
    if (currentIdx >= next.length) setCurrentIdx(Math.max(0, next.length - 1));
    if (next.length > 0) {
      const nextDraft = next[Math.min(currentIdx, next.length - 1)];
      setEditSubject(nextDraft.subject);
      setEditBody(nextDraft.body);
    }
  }

  async function skip() {
    if (currentIdx < drafts.length - 1) {
      goTo(currentIdx + 1);
    } else {
      goTo(0);
    }
    toast.info("Skipped");
  }

  async function regenerate() {
    if (!current) return;
    setRegenerating(true);
    try {
      const res = await fetch("/api/outreach/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ chefId: current.chefId, previousDraftId: current.id }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to regenerate");

      // Replace old draft in queue with the new one
      const newDraft: Draft = {
        ...data.draft,
        chef: current.chef,
        isAutoGenerated: true,
        dataPointsUsed: JSON.stringify(data.dataPointsUsed),
        confidence: data.confidence,
        previousDraftId: current.id,
      };

      // Mark old draft as archived
      await fetch(`/api/outreach/drafts/${current.id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: "archived" }),
      });

      const updated = [...drafts];
      updated[currentIdx] = newDraft;
      setDrafts(updated);
      setEditSubject(newDraft.subject);
      setEditBody(newDraft.body);
      toast.success("New draft generated!");
    } catch (err) {
      toast.error((err as Error).message);
    } finally {
      setRegenerating(false);
    }
  }

  async function autoDraftAll() {
    setAutoGenerating(true);
    setAutoProgress("Finding chefs without drafts...");
    try {
      // Get all chefs
      const chefsRes = await fetch("/api/chefs?limit=200");
      const chefsData = await chefsRes.json();
      const allChefs = chefsData.chefs || [];

      // Get existing drafts
      const draftsRes = await fetch("/api/outreach/drafts?limit=200");
      const draftsData = await draftsRes.json();
      const existingChefIds = new Set((draftsData.drafts || [])
        .filter((d: Draft) => d.status !== "archived")
        .map((d: Draft) => d.chefId));

      // Filter to chefs without pending drafts
      const chefsNeedingDrafts = allChefs.filter((c: Chef) => !existingChefIds.has(c.id));

      if (chefsNeedingDrafts.length === 0) {
        toast.info("All chefs already have pending drafts!");
        setAutoGenerating(false);
        setAutoProgress("");
        return;
      }

      const chefIds = chefsNeedingDrafts.map((c: Chef) => c.id);
      setAutoProgress(`Generating drafts for ${chefIds.length} chefs...`);

      const res = await fetch("/api/outreach/generate-batch", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ chefIds }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Batch generation failed");

      toast.success(`Generated ${data.success} drafts (${data.failed} failed)`);
      fetchDrafts();
    } catch (err) {
      toast.error((err as Error).message);
    } finally {
      setAutoGenerating(false);
      setAutoProgress("");
    }
  }

  const dataPoints: string[] = current?.dataPointsUsed ? (() => { try { return JSON.parse(current.dataPointsUsed); } catch { return []; } })() : [];

  if (loading) return <Skeleton className="h-96" />;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold">Review Queue</h2>
          <p className="text-sm text-muted-foreground">
            {drafts.length} auto-generated draft{drafts.length !== 1 ? "s" : ""} to review
          </p>
        </div>
        <Button onClick={autoDraftAll} disabled={autoGenerating}>
          {autoGenerating ? <Loader2 className="h-4 w-4 mr-1 animate-spin" /> : <Sparkles className="h-4 w-4 mr-1" />}
          {autoGenerating ? autoProgress || "Generating..." : "Auto-Draft All"}
        </Button>
      </div>

      {drafts.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <ListChecks className="h-10 w-10 mx-auto mb-3 text-muted-foreground/30" />
            <p className="text-sm font-medium text-muted-foreground">No drafts to review</p>
            <p className="text-xs text-muted-foreground mt-1">Generate drafts from chef profiles or use Auto-Draft All above.</p>
          </CardContent>
        </Card>
      ) : current && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Link href={`/chefs/${current.chef.slug}`} className="hover:underline">{current.chef.name}</Link>
                {current.chef.currentRestaurant && <span className="text-sm text-muted-foreground">at {current.chef.currentRestaurant}</span>}
                {current.confidence && (
                  <Badge variant={current.confidence === "high" ? "default" : current.confidence === "medium" ? "secondary" : "destructive"} className="text-xs">
                    {current.confidence}
                  </Badge>
                )}
              </div>
              <span className="text-sm text-muted-foreground font-normal">
                {currentIdx + 1} of {drafts.length}
              </span>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label>Subject</Label>
              <Input value={editSubject} onChange={(e) => setEditSubject(e.target.value)} />
            </div>
            <div>
              <Label>Body</Label>
              <Textarea value={editBody} onChange={(e) => setEditBody(e.target.value)} rows={10} className="font-mono text-sm" />
            </div>
            {dataPoints.length > 0 && (
              <p className="text-xs text-muted-foreground">
                <span className="font-medium">Referenced: </span>{dataPoints.join(" | ")}
              </p>
            )}
            <Separator />
            <div className="flex items-center gap-2 flex-wrap">
              <Button onClick={approve} className="gap-1">
                <Check className="h-4 w-4" /> Approve
              </Button>
              <Button variant="outline" onClick={regenerate} disabled={regenerating} className="gap-1">
                {regenerating ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
                Try Again
              </Button>
              <Button variant="outline" onClick={skip} className="gap-1">
                <SkipForward className="h-4 w-4" /> Skip
              </Button>
              <div className="flex-1" />
              <Button variant="ghost" size="sm" onClick={async () => {
                await navigator.clipboard.writeText(`Subject: ${editSubject}\n\n${editBody}`);
                setCopied(true);
                toast.success("Copied!");
                setTimeout(() => setCopied(false), 2000);
              }}>
                {copied ? <Check className="h-3 w-3 mr-1" /> : <ClipboardCopy className="h-3 w-3 mr-1" />}
                {copied ? "Copied!" : "Copy"}
              </Button>
              <div className="flex items-center gap-1">
                <Button variant="ghost" size="icon" disabled={currentIdx === 0} onClick={() => goTo(currentIdx - 1)}>
                  <ChevronLeft className="h-4 w-4" />
                </Button>
                <Button variant="ghost" size="icon" disabled={currentIdx >= drafts.length - 1} onClick={() => goTo(currentIdx + 1)}>
                  <ChevronRight className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
