-- CreateTable
CREATE TABLE "OutreachSettings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "purpose" TEXT NOT NULL DEFAULT 'We want to connect one-on-one to understand what top chefs look for in an assistant, what tools and support they rely on, and what''s missing.',
    "tone" TEXT NOT NULL DEFAULT 'warm',
    "maxWords" INTEGER NOT NULL DEFAULT 150
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_OutreachDraft" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "chefId" TEXT NOT NULL,
    "templateId" TEXT,
    "toEmail" TEXT,
    "subject" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'drafted',
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "dataPointsUsed" TEXT,
    "confidence" TEXT,
    "previousDraftId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "OutreachDraft_chefId_fkey" FOREIGN KEY ("chefId") REFERENCES "Chef" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_OutreachDraft" ("body", "chefId", "createdAt", "id", "status", "subject", "templateId", "toEmail", "updatedAt") SELECT "body", "chefId", "createdAt", "id", "status", "subject", "templateId", "toEmail", "updatedAt" FROM "OutreachDraft";
DROP TABLE "OutreachDraft";
ALTER TABLE "new_OutreachDraft" RENAME TO "OutreachDraft";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
